# Generated by Django 4.2.30 on 2026-06-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=200)),
                ('tagline', models.CharField(blank=True, default='', max_length=500)),
                ('show_profile_pic', models.BooleanField(default=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('accent_color', models.CharField(default='#6366f1', max_length=7)),
                ('font_family', models.CharField(default='Inter', max_length=100)),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('card', 'Card'), ('paragraph', 'Paragraph'), ('skills', 'Skills'), ('timeline', 'Timeline'), ('gallery', 'Gallery'), ('embed', 'Embed')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blocks/')),
                ('link', models.URLField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('tags', models.TextField(blank=True, default='', help_text='Comma-separated skill tags')),
                ('timeline_date', models.CharField(blank=True, default='', max_length=100)),
                ('timeline_title', models.CharField(blank=True, default='', max_length=300)),
                ('timeline_description', models.TextField(blank=True, default='')),
                ('embed_url', models.URLField(blank=True, default='')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='portfolio.section')),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'ordering': ['order'],
            },
        ),
    ]
