# Generated by Django 4.2.30 on 2026-06-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_intro',
            field=models.CharField(default="Hello, I'm", max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='New York, USA', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Full Stack Developer', max_length=200),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='dark', max_length=10),
        ),
    ]
