# Generated by Django 4.2.30 on 2026-06-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_custom_intro_profile_location_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
