# Generated by Django 4.2.30 on 2026-06-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_ats_button',
            field=models.BooleanField(default=True),
        ),
    ]
