# Generated by Django 4.2.30 on 2026-06-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_profile_show_ats_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10),
        ),
    ]
