# Generated by Django 4.2.30 on 2026-06-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_themesettings_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='blocks/files/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='profiles/resumes/'),
        ),
    ]
