# Generated by Django 4.2.30 on 2026-06-20 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0008_contentblock_file_profile_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Master switch for access')),
                ('access_type', models.CharField(choices=[('trial', 'Trial'), ('paid', 'Paid'), ('lifetime', 'Lifetime')], default='trial', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When access expires (null = no expiry set)', null=True)),
                ('blocked_by_admin', models.BooleanField(default=False, help_text='Admin can manually block access')),
                ('block_reason', models.CharField(blank=True, default='', help_text='Reason shown to user when blocked', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Access',
                'verbose_name_plural': 'User Access',
                'ordering': ['-created_at'],
            },
        ),
    ]
